name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - tomcat-10
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 9-jdk8
          - 9-jdk17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            TOMCAT_VERSION=${{ matrix.version }}
          tags: universityofwarwick/dev-tomcat:${{ matrix.version }}
